api/urls.py
from django.urls import path

from .views import api


urlpatterns = [
    path('', api)
]

dashboard/urls.py
from django.urls import path
from .viewss import (shopFormView,
 profileView,
 profileSettingsView,
 shopFormUpdateView, 
 shopFormDeleteView,
 supportsView)
from dashboard.views.order_views import (OrderView,
    mark_as_delivered,
    update_status,
    filater,
    add_order,
    remove_order,
    search)
from dashboard.views.product_view import (
    ProductView,
    # edit_product,
    product_edit_view,
    view_product_view,
    product_order_view)
from dashboard.views.customers_views import(
    customers_view
)
from dashboard.views.mail_views import (
    mail_view,
    compose_view,
    inbox_view
)
from dashboard.views.settings_views import (
    settings_view
)
from dashboard.views.dashboard_views import (
    dashboard_view
)

app_name = 'dashboard'

urlpatterns = [
    # dasboard urls

    path('', dashboard_view, name='dashboard'), 


    path('shopform/', shopFormView, name='shopform'),
    path('product-list/', ProductView, name='shoplist'),
    path('product-list/<str:slug>/edit/', shopFormUpdateView, name='shop-update'),
    path('product-list/<str:slug>/remove/', shopFormDeleteView, name='shop-delete'),
    path('order-list/', OrderView, name='shop-order-list'),
    path('user-profile/', profileView, name='user-profile'),
    path('user-profile-settings/', profileSettingsView, name='user-profile-settings'),
    path('support/', supportsView, name='support'),
    path('mark_as_delivered/<int:id>/', mark_as_delivered, name='mark_as_delivered'),
    path('update_status/<id>', update_status, name='update_status'),
    path('filater/<q>/', filater, name='filater'),
    path('add_order/', add_order, name='add_order'),
    path('remove_order/<int:id>/', remove_order, name='remove_order'),
    path('search/', search, name='search'),

    # product urls

    # path('edit_product/<int:id>/', edit_product, name='edit_product'),
    path('edit_product_view/<int:id>/', product_edit_view, name='product_edit_view'),
    path('view_product/<int:id>/', view_product_view, name='view_product'),
    path('product_order/<int:id>/', product_order_view, name='product_order'),

    # Customers urls

    path('customers/', customers_view, name='customers'),

    # Mail urls

    path('mail/', mail_view, name='mail'),
    path('compose/', compose_view, name='compose'),
    path('inbox/', inbox_view, name='inbox'),

    # Settings urls

    path('settings/', settings_view, name='settings')
]

my_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('gallery/', include('gallery.urls')),
    path('shop/', include('shop.urls')),
    path('accont/', include('acconts.urls')),
    path('cart/', include('cart.urls')),
    path('music/', include('music.urls')),
    path('api/', include('api.urls')),
    path('dashboard/', include('dashboard.urls'))
]

if (settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class Customers(AbstractUser):
    ordered = models.IntegerField(blank=True, default=0)
    phone = models.CharField(max_length=10, blank=True)
    groups = models.ManyToManyField(User, related_name='customer', blank=True)
    user_permissions = models.ManyToManyField(User, related_name='my_customer_permissions', blank=True)
    	
    last_order = models.CharField(max_length=100, blank=True)

class Mail(models.Model):
    STATE = (
        ('inbox', 'inbox'),
        ('draft', 'draft'),
        ('favourite', 'favourite'),
        ('sent', 'sent'),
        ('spam', 'spam'),
        ('trash', 'trash'),
        ('all_mails', 'all mails')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mail')
    subject = models.CharField(max_length=120)
    to = models.EmailField(help_text='Recipient')
    from_email = models.EmailField()
    messege = models.TextField()
    state = models.CharField(max_length=120, choices=STATE)

    def __str__(self):
        return ('Mail for {}').format(self.user.username)

class Setting(models.Model):
    store_name = models.CharField(max_length=120, blank=True, default='')
    site_email = models.EmailField(blank=True, default='')
    site_copyright = models.CharField(max_length=250, blank=True, default='')
    allow_registration = models.BooleanField(blank=True, default=True)
    main_website = models.URLField(blank=True, default='')
    maintanance_mode = models.BooleanField(blank=True, default=False)

    # Pay fast settings

    merchant_id = models.CharField(max_length=120, blank=True, default='')
    merchant_key = models.CharField(max_length=120, blank=True, default='')

    def __str__(self):
        return self.stmore_name


class Sale(models.Model):
    total_sales = models.IntegerField(blank=True, default=0)
    averarge_order = models.IntegerField(blank=True, default=0)
    orders = models.IntegerField(blank=True, default=0)
    customers = models.IntegerField(blank=True, default=0)
    slug = models.SlugField(blank=True, default='sales')

    def __str__(self):
        return ('my dashboard')

dashboard/forms/mail_forms.py
from django import forms
from dashboard.models import Mail

class MailModelForm(forms.ModelForm):
    class Meta:
        model = Mail
        fields = '__all__'

dashboard/forms/order_forms.py
from django import forms
from cart.models import Transaction, Order

class UpdateStatusModelForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['status',]

class AddOrderModelForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['items',]

dashboard/forms/product_forms.py
from django import forms
from shop.models import *

class UpdateProductModelForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'

        widgets = {
            'image': forms.FileInput(attrs={'class': 'custom-file-input', 'id':'customFile'}),
            'descirption': forms.Textarea(attrs={'class': 'form-control'})
        }


# class EditProductModelForm(forms.ModelForm):
#     class 

dashboard/forms/settings_forms.py
from django import forms
from dashboard.models import Setting

class SettingModelForm(forms.ModelForm):
    class Meta:
        model = Setting
        fields = '__all__'

        widgets = {
            'allow_registration': forms.RadioSelect(attrs={'class': 'custom-control-input', 'name': 'reg-public'}),
            'maintanance_mode': forms.CheckboxInput(attrs={'class': 'custom-control-input'})
        }

dashboard/views/customers_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from dashboard.models import Customers

def customers_view(request):
    template = 'dashboard/customers.html'
    customers = Customers.objects.filter(is_staff=False, is_superuser=False)
    context = {
        'customers': customers
    }
    return render(request, template, context)

dashboard/views/dashboard_views.py
from django.shortcuts import render, redirect, get_object_or_404
from dashboard.models import Sale

def dashboard_view(request):
    template = 'dashboard/dashboard.html'
    dashboard = get_object_or_404(Sale, slug='sales')
    context = {
        'dashboard': dashboard
    }
    return render(request, template, context)

dashboard/views/mail_views.py
from django.shortcuts import render, redirect, get_object_or_404
from dashboard.forms.mail_forms import MailModelForm

def mail_view(request):
    template = 'dashboard/mail.html'
    context = {}
    return render(request, template, context)

def compose_view(request):
    template = 'dashboard/mail.html'
    form = MailModelForm(request.POST or None)
    context = {
        'compose_form': form
    }
    return render(request, template, context)

def inbox_view(request):
    template = 'dashboard/mail/inbox.html'    

    return render(request, template)

dashboard/views/order_views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.models import *
from django.core.paginator import Paginator
from django.contrib import messages
from dashboard.forms.order_forms import UpdateStatusModelForm, AddOrderModelForm
from django.db.models import Q


def OrderView(request):
    transaction = Transaction.objects.all()
    form = UpdateStatusModelForm()

    paginator = Paginator(transaction, 10) 
    query = request.GET.get('page')

    page_obj = paginator.get_page(query)

    context = {
        'transaction': transaction,
        'page_obj': page_obj,
        'form': form
    }

    return render(request, 'dashboard/ordes.html', context)

def mark_as_delivered(request, id):
    transaction = Transaction.objects.get(id=id)
    obj = transaction
    if obj.status != 'Delivered':
        obj.status = 'Delivered'
        obj.save()
        messages.success(request, f'marked as delivered')
    else:
        messages.warning(request, f'already mark as delivered')
    return redirect('shop-order-list')

def update_status(request, id):
    transaction = Transaction.objects.get(id=id)
    form = UpdateStatusModelForm(request.POST or None, instance=transaction)
    if form.is_valid():
        form.save()
        messages.success(request, f' Status Succesfuly Updated')
    else:
        messages.warning(request, f'already mark as delivered')
    return redirect('shop-order-list')

def filater(request, q):
    print(q)
    transaction = Transaction.objects.filter(status=q)

    paginator = Paginator(transaction, 10) 
    query = request.GET.get('page')

    page_obj = paginator.get_page(query)
    form = UpdateStatusModelForm()
    add_order_form = AddOrderModelForm()
    context = {
        'page_obj': page_obj,
        'form': form,
        'add_order_form': add_order_form
    }

    return render(request, 'dashboard/ordes.html', context)

def add_order(request):
    add_order_form = AddOrderModelForm(request.POST or None)
    if add_order_form.is_valid():
        add_order_form.save()
        return redirect('filater')

def remove_order(request, id):
    order_remove = get_object_or_404(Transaction, id=id)

    order_remove.delete()
    messages.success(request, f'order removed')
    return redirect('shop-order-list')
    
def search(request):
    template = 'dashboard/ordes.html'
    query = request.GET.get('q')
    if query:
        results = Transaction.objects.filter(Q(id__icontains=query) | Q(order_id__icontains=query))
    else:
        results = Transaction.objects.all()

    Qs = request.GET.get('page')
    paginator = Paginator(results, 10) # Show 10 contacts per page.
    page_obj = paginator.get_page(Qs)
    return render(request, template, {'page_obj': page_obj, 'query': query})

dashboard/views/product_view.py
from django.shortcuts import redirect, render, get_object_or_404
from shop.models import Shop, ColorVarient
from django.core.paginator import Paginator
from dashboard.forms.product_forms import UpdateProductModelForm
from django.contrib import messages
from cart.models import Order, OrderItem
from django.db.models import Q


def ProductView(request):

    shop_list = Shop.objects.all()
    form = UpdateProductModelForm()
    # paginator
    paginator = Paginator(shop_list, 10) 
    query = request.GET.get('page')

    page_obj = paginator.get_page(query)


    context = {
        'shop_list': shop_list,
        'page_obj': page_obj,
        'form': form
    }

    return render(request, 'dashboard/product.html', context)

def edit_product(request, id):
    product = get_object_or_404(Shop, id=id)
    form = UpdateProductModelForm(request.POST or None, instance=product)
    if form.is_valid():
        form.save()
        messages.success(request, f'product updated')
        return redirect('shoplist')

def product_edit_view(request, id):
    product = get_object_or_404(Shop, id=id)
    template = 'dashboard/product_edit.html'
    form = UpdateProductModelForm(request.POST or None, instance=product)
    context = {
        'form': form,
        'product': product
    }
    return render(request, template, context)

def view_product_view(request, id):
    template = 'dashboard/product_view.html'

    product = get_object_or_404(Shop, id=id)
    colors = ColorVarient.objects.filter(product=product)
    context = {
        'product': product,
        'colors': colors
    }
    return render(request, template, context)

def product_order_view(request, id):
    template = 'dashboard/product_order.html'
    product = Shop.objects.get(id=id)
    order = OrderItem.objects.filter(product=product)
    
    context = {
        'order': order,
        'product': product
    }
    return render(request, template, context)

dashboard/views/settings_views.py
from django.shortcuts import render, redirect, get_object_or_404
from dashboard.models import Setting
from dashboard.forms.settings_forms import SettingModelForm

def settings_view(request):
    template = 'dashboard/settings.html'
    setting,created = Setting.objects.get_or_create()
    form = SettingModelForm(request.POST or None, instance=setting)
    context = {
        'form': form
    }
    return render(request, template, context)

dashboard/templates/dashboard/mail.html
{% extends 'dashboard/mail/base(mail).html' %}
{% load crispy_forms_tags %}
{% block mail %}

{% endblock %}

dashboard/templates/dashboard/ordes.html
{% extends 'base(dashboard).html' %}
{% block content %}
<div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                <div class="nk-block-head nk-block-head-sm">
                    <div class="nk-block-between">
                        <div class="nk-block-head-content">
                            <h3 class="nk-block-title page-title">Orders</h3>
                        </div><!-- .nk-block-head-content -->
                        <div class="nk-block-head-content">
                            <div class="toggle-wrap nk-block-tools-toggle">
                                <a href="#" class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em class="icon ni ni-more-v"></em></a>
                                <div class="toggle-expand-content" data-content="pageMenu">
                                    <ul class="nk-block-tools g-3">
                                        <li>
                                            <div class="form-control-wrap">
                                                <form action="{% url 'dashboard:search' %}">
                                                <div class="form-icon form-icon-right">
                                                    <em class="icon ni ni-search"></em>
                                                </div>
                                                    <input name="q" class="form-control" id="default-04" placeholder="Quick search ...">
                                                </form>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="drodown">
                                                <a href="#" class="dropdown-toggle dropdown-indicator btn btn-outline-light btn-white" data-toggle="dropdown">Status</a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <ul class="link-list-opt no-bdr">
                                                        <li><a href="{% url 'dashboard:filater' q='On Hold' %}" ><span>On Hold</span></a></li>
                                                        <li><a href="{% url 'dashboard:filater' q='Delivered' %}" name='delevired'><span>Delevired</span></a></li>
                                                        <li><a href="{% url 'dashboard:filater' q='Not Delivered' %}" name='rejected'><span>Rejected</span></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="nk-block-tools-opt">
                                            <a href="#" class="btn btn-icon btn-primary d-md-none"><em class="icon ni ni-plus"></em></a>
                                            <a href="#" data-toggle="modal" data-target="#add_order" class="btn btn-primary d-none d-md-inline-flex"><em class="icon ni ni-plus"></em><span>Add Order</span></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .nk-block-head-content -->
                    </div><!-- .nk-block-between -->
                </div><!-- .nk-block-head -->
                <div class="nk-block">
                    <div class="nk-tb-list is-separate is-medium mb-3">
                        <div class="nk-tb-item nk-tb-head">
                            <div class="nk-tb-col nk-tb-col-check">
                                <div class="custom-control custom-control-sm custom-checkbox notext">
                                    <input type="checkbox" class="custom-control-input" id="uid">
                                    <label class="custom-control-label" for="uid"></label>
                                </div>
                            </div>
                            <div class="nk-tb-col"><span>Order</span></div>
                            <div class="nk-tb-col tb-col-md"><span>Date</span></div>
                            <div class="nk-tb-col"><span class="d-none d-mb-block">Status</span></div>
                            <div class="nk-tb-col tb-col-sm"><span>Customer</span></div>
                            <div class="nk-tb-col tb-col-md"><span>Purchased</span></div>
                            <div class="nk-tb-col"><span>Total</span></div>
                            <div class="nk-tb-col nk-tb-col-tools">
                                <ul class="nk-tb-actions gx-1 my-n1">
                                    <li>
                                        <div class="drodown">
                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger mr-n1" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <ul class="link-list-opt no-bdr">
                                                    <li><a href="#"><em class="icon ni ni-truck"></em><span>Mark as Delivered</span></a></li>
                                                    <li><a href="#"><em class="icon ni ni-trash"></em><span>Remove Orders</span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- .nk-tb-item -->
                        {% if page_obj %}
                        {% for order in page_obj %}
                        {% include 'dashboard/modals/orders_modals/update_status.html' %}
                        <div class="nk-tb-item">
                            <div class="nk-tb-col nk-tb-col-check">
                                <div class="custom-control custom-control-sm custom-checkbox notext">
                                    <input type="checkbox" class="custom-control-input" id="{{ order.id }}">
                                    <label class="custom-control-label" for="{{ order.id }}"></label>
                                </div>
                            </div>
                            <div class="nk-tb-col">
                                <span class="tb-lead"><a href="#">#{{ order.order_id }}</a></span>
                            </div>
                            <div class="nk-tb-col tb-col-md">
                                <span class="tb-sub">{{ order.timestamp }}</span>
                            </div>
                            <div class="nk-tb-col">
                                <span class="dot bg-warning d-mb-none"></span>
                                <span class="badge badge-sm badge-dot has-bg badge-{% if order.delivered %}success{% else %}warning{% endif %} d-none d-mb-inline-flex">{{ order.status }}</span>
                            </div>
                            <div class="nk-tb-col tb-col-sm">
                                <span class="tb-sub">{{ order.profile.user.username }}</span>
                            </div>
                            <div class="nk-tb-col tb-col-md">
                                <span class="tb-sub text-primary">{{ order.purchesed_items.count }} Items</span>
                            </div>
                            <div class="nk-tb-col">
                                <span class="tb-lead">R {{ order.total }}</span>
                            </div>
                            <div class="nk-tb-col nk-tb-col-tools">
                                <ul class="nk-tb-actions gx-1">
                                    <li class="nk-tb-action-hidden"><a href="#" class="btn btn-icon btn-trigger btn-tooltip" title="View Order" data-toggle="dropdown">
                                            <em class="icon ni ni-eye"></em></a></li>
                                    <li>
                                        <div class="drodown mr-n1">
                                            <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <ul class="link-list-opt no-bdr">
                                                    <li><a href="#" data-toggle="modal" data-target="#update_status"><em class="icon ni ni-edit"></em><span>Update Status</span></a></li>
                                                    <li><a href="{% url 'dashboard:mark_as_delivered' id=order.id %}"><em class="icon ni ni-truck"></em><span>Mark as Delivered</span></a></li>
                                                    <li><a href="{% url 'dashboard:remove_order' id=order.id %}"><em class="icon ni ni-trash"></em><span>Remove Order</span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- .nk-tb-item -->
                        {% endfor %}
                        {% else %}
                        <div class="nk-content " >
                            <p>No Orders</p>
                        </div>
                        {% endif %}

                    </div><!-- .nk-tb-list -->
                    {% if page_obj %}
                    <div class="card">
                        <div class="card-inner">
                            <div class="nk-block-between-md g-3">
                                <div class="g">
                                    <nav>
                                        <ul class="pagination">
                                            {% if page_obj.has_previous %}
                                            <li class="page-item disabled"><a class="page-link" href="?page=1">First</a></li>
                                            <li class="page-item"><a class="page-link"  href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                            {% endif %}
                                                <!-- <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ page_obj.number }}<span class="sr-only">(current)</span></a></li> -->
                                            {% for num in page_obj.paginator.page_range %}
                                                {% if page_obj.number == num %}
                                                <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            <!-- <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li> -->
                                            {% if page_obj.has_next %}
                                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                                <div class="g">
                                    <div class="pagination-goto d-flex justify-content-center justify-content-md-start gx-3">
                                        <div>Page</div>
                                        <div>
                                            <select class="form-select form-select-sm" data-search="on" data-dropdown="xs center">
                                                {% for num in page_obj.paginator.page_range %}
                                                <option value="page-{{ num }}"><a class="page-link" href="?page={{ num }}">{{ num }}</a></option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div>OF {{ page_obj.paginator.num_pages }}</div>
                                    </div>
                                </div><!-- .pagination-goto -->
                            </div><!-- .nk-block-between -->
                        </div>
                    </div>
                    {% endif %}
                </div><!-- .nk-block -->
            </div>
        </div>
    </div>
</div>
{% include 'dashboard/modals/orders_modals/add_order.html' %}
{% endblock %}

dashboard/templates/dashboard/product_view.html
{% extends 'base(dashboard).html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="nk-block nk-block-lg">
    <div class="nk-block-head">
        <div class="nk-block-head-content">
            <h4 class="title nk-block-title">Edit product</h4>
            <div class="nk-block-des">
                <p>You can edit your product here.</p>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-inner">
            <div class="card-head">
                <h5 class="card-title">Product View</h5>
            </div>
            <div class="row g-4">
                <div class="col-lg-6">
                    <img src="{{ product.image.url }}" alt="">
                </div>
                <div class="col-lg-6">
                    <div class="pb-3">
                        <h6>Product Name: </h6> 
                    </div>
                    <h4>{{ product.title }}</h4>
                    <div>
                        <div>
                            <h6>Category: </h6>
                        </div>
                        <div class="p-2">
                            <p>{{ product.category }}</p>
                        </div>
                    </div>
                    <div>
                        <div>
                            <h6>Price:</h6>
                        </div>
                        <div class="p-2">
                            <h5>R {{ product.price }}</h5>
                        </div>
                    </div>
                    <div>
                        <div>
                            <h6>Descirption:</h6>
                        </div>
                        <div class="p-2">
                            <p>{{ product.descirption }}</p>
                        </div>
                    </div>
                    <div>
                        <div class="pb-2"><h6>Colors</h6></div>
                        {% for color in product.color.all %}
                            <div class="badge bg-{{ color.color }}">_</div>
                        {% endfor %}
                    </div>
                    <div>
                        <div class="pt-2"><h6>Size</h6></div>
                        {% for size in product.size.all %}
                            <div><p>{{ size.size }}</p></div>
                        {% endfor %} 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}