api/urls.py
from django.urls import path

from .views import api


urlpatterns = [
    path('', api)
]

dashboard/urls.py
from django.urls import path
from .viewss import (shopFormView,
 profileView,
 profileSettingsView,
 shopFormUpdateView, 
 shopFormDeleteView,
 supportsView)
from dashboard.views.order_views import (OrderView,
    mark_as_delivered,
    update_status,
    filater,
    add_order,
    remove_order,
    search)
from dashboard.views.product_view import (
    ProductView,
    # edit_product,
    product_edit_view,
    view_product_view,
    product_order_view)
from dashboard.views.customers_views import(
    customers_view
)
from dashboard.views.mail_views import (
    mail_view,
    compose_view,
    inbox_view
)
from dashboard.views.settings_views import (
    settings_view
)
from dashboard.views.dashboard_views import (
    dashboard_view
)

app_name = 'dashboard'

urlpatterns = [
    # dasboard urls

    path('', dashboard_view, name='dashboard'), 


    path('shopform/', shopFormView, name='shopform'),
    path('product-list/', ProductView, name='shoplist'),
    path('product-list/<str:slug>/edit/', shopFormUpdateView, name='shop-update'),
    path('product-list/<str:slug>/remove/', shopFormDeleteView, name='shop-delete'),
    path('order-list/', OrderView, name='shop-order-list'),
    path('user-profile/', profileView, name='user-profile'),
    path('user-profile-settings/', profileSettingsView, name='user-profile-settings'),
    path('support/', supportsView, name='support'),
    path('mark_as_delivered/<int:id>/', mark_as_delivered, name='mark_as_delivered'),
    path('update_status/<id>', update_status, name='update_status'),
    path('filater/<q>/', filater, name='filater'),
    path('add_order/', add_order, name='add_order'),
    path('remove_order/<int:id>/', remove_order, name='remove_order'),
    path('search/', search, name='search'),

    # product urls

    # path('edit_product/<int:id>/', edit_product, name='edit_product'),
    path('edit_product_view/<int:id>/', product_edit_view, name='product_edit_view'),
    path('view_product/<int:id>/', view_product_view, name='view_product'),
    path('product_order/<int:id>/', product_order_view, name='product_order'),

    # Customers urls

    path('customers/', customers_view, name='customers'),

    # Mail urls

    path('mail/', mail_view, name='mail'),
    path('compose/', compose_view, name='compose'),
    path('inbox/', inbox_view, name='inbox'),

    # Settings urls

    path('settings/', settings_view, name='settings')
]

my_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('gallery/', include('gallery.urls')),
    path('shop/', include('shop.urls')),
    path('accont/', include('acconts.urls')),
    path('cart/', include('cart.urls')),
    path('music/', include('music.urls')),
    path('api/', include('api.urls')),
    path('dashboard/', include('dashboard.urls'))
]

if (settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class Customers(AbstractUser):
    ordered = models.IntegerField(blank=True, default=0)
    phone = models.CharField(max_length=10, blank=True)
    groups = models.ManyToManyField(User, related_name='customer', blank=True)
    user_permissions = models.ManyToManyField(User, related_name='my_customer_permissions', blank=True)
    	
    last_order = models.CharField(max_length=100, blank=True)

class Mail(models.Model):
    STATE = (
        ('inbox', 'inbox'),
        ('draft', 'draft'),
        ('favourite', 'favourite'),
        ('sent', 'sent'),
        ('spam', 'spam'),
        ('trash', 'trash'),
        ('all_mails', 'all mails')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='mail')
    subject = models.CharField(max_length=120)
    to = models.EmailField(help_text='Recipient')
    from_email = models.EmailField()
    messege = models.TextField()
    state = models.CharField(max_length=120, choices=STATE)

    def __str__(self):
        return ('Mail for {}').format(self.user.username)

class Setting(models.Model):
    store_name = models.CharField(max_length=120, blank=True, default='')
    site_email = models.EmailField(blank=True, default='')
    site_copyright = models.CharField(max_length=250, blank=True, default='')
    allow_registration = models.BooleanField(blank=True, default=True)
    main_website = models.URLField(blank=True, default='')
    maintanance_mode = models.BooleanField(blank=True, default=False)

    # Pay fast settings

    merchant_id = models.CharField(max_length=120, blank=True, default='')
    merchant_key = models.CharField(max_length=120, blank=True, default='')

    def __str__(self):
        return self.stmore_name


class Sale(models.Model):
    total_sales = models.IntegerField(blank=True, default=0)
    averarge_order = models.IntegerField(blank=True, default=0)
    orders = models.IntegerField(blank=True, default=0)
    customers = models.IntegerField(blank=True, default=0)
    slug = models.SlugField(blank=True, default='sales')

    def __str__(self):
        return ('my dashboard')

dashboard/forms/mail_forms.py
from django import forms
from dashboard.models import Mail

class MailModelForm(forms.ModelForm):
    class Meta:
        model = Mail
        fields = '__all__'

dashboard/forms/order_forms.py
from django import forms
from cart.models import Transaction, Order

class UpdateStatusModelForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['status',]

class AddOrderModelForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['items',]

dashboard/forms/product_forms.py
from django import forms
from shop.models import *

class UpdateProductModelForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'

        widgets = {
            'image': forms.FileInput(attrs={'class': 'custom-file-input', 'id':'customFile'}),
            'descirption': forms.Textarea(attrs={'class': 'form-control'})
        }


# class EditProductModelForm(forms.ModelForm):
#     class 

dashboard/forms/settings_forms.py
from django import forms
from dashboard.models import Setting

class SettingModelForm(forms.ModelForm):
    class Meta:
        model = Setting
        fields = '__all__'

        widgets = {
            'allow_registration': forms.RadioSelect(attrs={'class': 'custom-control-input', 'name': 'reg-public'}),
            'maintanance_mode': forms.CheckboxInput(attrs={'class': 'custom-control-input'})
        }

dashboard/views/customers_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from dashboard.models import Customers

def customers_view(request):
    template = 'dashboard/customers.html'
    customers = Customers.objects.filter(is_staff=False, is_superuser=False)
    context = {
        'customers': customers
    }
    return render(request, template, context)

dashboard/views/dashboard_views.py
from django.shortcuts import render, redirect, get_object_or_404
from dashboard.models import Sale

def dashboard_view(request):
    template = 'dashboard/dashboard.html'
    dashboard = get_object_or_404(Sale, slug='sales')
    context = {
        'dashboard': dashboard
    }
    return render(request, template, context)

dashboard/views/mail_views.py
from django.shortcuts import render, redirect, get_object_or_404
from dashboard.forms.mail_forms import MailModelForm

def mail_view(request):
    template = 'dashboard/mail.html'
    context = {}
    return render(request, template, context)

def compose_view(request):
    template = 'dashboard/mail.html'
    form = MailModelForm(request.POST or None)
    context = {
        'compose_form': form
    }
    return render(request, template, context)

def inbox_view(request):
    template = 'dashboard/mail/inbox.html'    

    return render(request, template)

dashboard/views/order_views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.models import *
from django.core.paginator import Paginator
from django.contrib import messages
from dashboard.forms.order_forms import UpdateStatusModelForm, AddOrderModelForm
from django.db.models import Q


def OrderView(request):
    transaction = Transaction.objects.all()
    form = UpdateStatusModelForm()

    paginator = Paginator(transaction, 10) 
    query = request.GET.get('page')

    page_obj = paginator.get_page(query)

    context = {
        'transaction': transaction,
        'page_obj': page_obj,
        'form': form
    }

    return render(request, 'dashboard/ordes.html', context)

def mark_as_delivered(request, id):
    transaction = Transaction.objects.get(id=id)
    obj = transaction
    if obj.status != 'Delivered':
        obj.status = 'Delivered'
        obj.save()
        messages.success(request, f'marked as delivered')
    else:
        messages.warning(request, f'already mark as delivered')
    return redirect('shop-order-list')

def update_status(request, id):
    transaction = Transaction.objects.get(id=id)
    form = UpdateStatusModelForm(request.POST or None, instance=transaction)
    if form.is_valid():
        form.save()
        messages.success(request, f' Status Succesfuly Updated')
    else:
        messages.warning(request, f'already mark as delivered')
    return redirect('shop-order-list')

def filater(request, q):
    print(q)
    transaction = Transaction.objects.filter(status=q)

    paginator = Paginator(transaction, 10) 
    query = request.GET.get('page')

    page_obj = paginator.get_page(query)
    form = UpdateStatusModelForm()
    add_order_form = AddOrderModelForm()
    context = {
        'page_obj': page_obj,
        'form': form,
        'add_order_form': add_order_form
    }

    return render(request, 'dashboard/ordes.html', context)

def add_order(request):
    add_order_form = AddOrderModelForm(request.POST or None)
    if add_order_form.is_valid():
        add_order_form.save()
        return redirect('filater')

def remove_order(request, id):
    order_remove = get_object_or_404(Transaction, id=id)

    order_remove.delete()
    messages.success(request, f'order removed')
    return redirect('shop-order-list')
    
def search(request):
    template = 'dashboard/ordes.html'
    query = request.GET.get('q')
    if query:
        results = Transaction.objects.filter(Q(id__icontains=query) | Q(order_id__icontains=query))
    else:
        results = Transaction.objects.all()

    Qs = request.GET.get('page')
    paginator = Paginator(results, 10) # Show 10 contacts per page.
    page_obj = paginator.get_page(Qs)
    return render(request, template, {'page_obj': page_obj, 'query': query})

dashboard/views/product_view.py
from django.shortcuts import redirect, render, get_object_or_404
from shop.models import Shop, ColorVarient
from django.core.paginator import Paginator
from dashboard.forms.product_forms import UpdateProductModelForm
from django.contrib import messages
from cart.models import Order, OrderItem
from django.db.models import Q


def ProductView(request):

    shop_list = Shop.objects.all()
    form = UpdateProductModelForm()
    # paginator
    paginator = Paginator(shop_list, 10) 
    query = request.GET.get('page')

    page_obj = paginator.get_page(query)


    context = {
        'shop_list': shop_list,
        'page_obj': page_obj,
        'form': form
    }

    return render(request, 'dashboard/product.html', context)

def edit_product(request, id):
    product = get_object_or_404(Shop, id=id)
    form = UpdateProductModelForm(request.POST or None, instance=product)
    if form.is_valid():
        form.save()
        messages.success(request, f'product updated')
        return redirect('shoplist')

def product_edit_view(request, id):
    product = get_object_or_404(Shop, id=id)
    template = 'dashboard/product_edit.html'
    form = UpdateProductModelForm(request.POST or None, instance=product)
    context = {
        'form': form,
        'product': product
    }
    return render(request, template, context)

def view_product_view(request, id):
    template = 'dashboard/product_view.html'

    product = get_object_or_404(Shop, id=id)
    colors = ColorVarient.objects.filter(product=product)
    context = {
        'product': product,
        'colors': colors
    }
    return render(request, template, context)

def product_order_view(request, id):
    template = 'dashboard/product_order.html'
    product = Shop.objects.get(id=id)
    order = OrderItem.objects.filter(product=product)
    
    context = {
        'order': order,
        'product': product
    }
    return render(request, template, context)

dashboard/views/settings_views.py
from django.shortcuts import render, redirect, get_object_or_404
from dashboard.models import Setting
from dashboard.forms.settings_forms import SettingModelForm

def settings_view(request):
    template = 'dashboard/settings.html'
    setting,created = Setting.objects.get_or_create()
    form = SettingModelForm(request.POST or None, instance=setting)
    context = {
        'form': form
    }
    return render(request, template, context)

dashboard/templates/base(dashboard).html
<!DOCTYPE html>
<html lang="zxx" class="js">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A powerful and conceptual apps base dashboard template that especially build for developers and programmers.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="{{ logo.favor_icon.url }}">
    <!-- Page Title  -->
    <title>Subscription Dashboard | DashLite Admin Template</title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="{% static 'assets-2/assets/css/dashlite.css' %}">
    <link id="skin-default" rel="stylesheet" href="{% static 'assets-2/assets/css/theme.css' %}">
</head>
<body class="nk-body bg-lighter npc-default has-sidebar ">
    <div class="nk-app-root">
        <!-- main @s -->
        <div class="nk-main ">
            <!-- sidebar @s -->
            <div class="nk-sidebar nk-sidebar-fixed is-light " data-content="sidebarMenu">
                <div class="nk-sidebar-element nk-sidebar-head">
                    <div class="nk-sidebar-brand">
                        <a href="{% url 'home' %}" class="logo-link nk-sidebar-logo">
                            <!-- <img class="logo-light logo-img" src="./images/logo.png" srcset="./images/logo2x.png 2x" alt="logo"> -->
                            <img class="logo-dark logo-img" style="height: 60px;width: 260px; max-width: 250%;" src="{{ logo.dashboard_dark.url }}" srcset="{{ logo.dashboard_dark.url }} 2x" alt="logo-dark">
                        </a>
                    </div>
                    <div class="nk-menu-trigger mr-n2">
                        <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
                        <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
                    </div>
                </div><!-- .nk-sidebar-element -->
                <div class="nk-sidebar-element">
                    <div class="nk-sidebar-content">
                        <div class="nk-sidebar-menu" data-simplebar>
                            <ul class="nk-menu">
                                <li class="nk-menu-item">
                                    <a href="{% url 'dashboard:dashboard' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-dashboard-fill"></em></span>
                                        <span class="nk-menu-text">Dashboard</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="{% url 'dashboard:shop-order-list' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-bag-fill"></em></span>
                                        <span class="nk-menu-text">Orders</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="{% url 'dashboard:shoplist' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-package-fill"></em></span>
                                        <span class="nk-menu-text">Products</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="{% url 'dashboard:customers' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-users-fill"></em></span>
                                        <span class="nk-menu-text">Customers</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="{% url 'dashboard:mail' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-mail-fill"></em></span>
                                        <span class="nk-menu-text">Mail</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="{% url 'dashboard:support' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-chat-fill"></em></span>
                                        <span class="nk-menu-text">Supports</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="{% url 'dashboard:settings' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-opt-alt-fill"></em></span>
                                        <span class="nk-menu-text">Settings</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-server-fill"></em></span>
                                        <span class="nk-menu-text">Integration</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-heading">
                                    <h6 class="overline-title text-primary-alt">Return to</h6>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="{% url 'home' %}" class="nk-menu-link" target="_blank">
                                        <span class="nk-menu-icon"><em class="icon ni ni-home-fill"></em></span>
                                        <span class="nk-menu-text">Home</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                            </ul><!-- .nk-menu -->
                        </div><!-- .nk-sidebar-menu -->
                    </div><!-- .nk-sidebar-content -->
                </div><!-- .nk-sidebar-element -->
            </div>
            <!-- sidebar @e -->
            <!-- wrap @s -->
            <div class="nk-wrap ">
                <!-- main header @s -->
                <div class="nk-header nk-header-fixed is-light">
                    <div class="container-fluid">
                        <div class="nk-header-wrap">
                            <div class="nk-menu-trigger d-xl-none ml-n1">
                                <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
                            </div>
                            <div class="nk-header-brand d-xl-none">
                                <a href="{% url 'home' %}" class="logo-link">
                                    <img class="logo-dark logo-img" style="height: 80px;width: 160px; max-width: 250%;" src="{% static 'assets-2/assets/logo/Noterio-logo-dark.png' %}" srcset="{% static 'logo/Noterio-logo.png' %} 2x" alt="logo-dark">
                                </a>
                            </div><!-- .nk-header-brand -->
                            <div class="nk-header-tools">
                                <ul class="nk-quick-nav">
                                    <li class="dropdown user-dropdown">
                                        <a href="#" class="dropdown-toggle mr-n1" data-toggle="dropdown">
                                            <div class="user-toggle">
                                                <div class="user-avatar sm">
                                                    <em class="icon ni ni-user-alt"></em>
                                                </div>
                                                <div class="user-info d-none d-xl-block">
                                                    <div class="user-status user-status-unverified">Free</div>
                                                    <div class="user-name dropdown-indicator">{{ user.username }}</div>
                                                </div>
                                            </div>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-right">
                                            <div class="dropdown-inner user-card-wrap bg-lighter d-none d-md-block">
                                                <div class="user-card">
                                                    <div class="user-avatar">
                                                        <span>{{ user.username }}</span>
                                                    </div>
                                                    <div class="user-info">
                                                        <span class="lead-text">{{ user.username }}</span>
                                                        <span class="sub-text">{{ user.email }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="dropdown-inner">
                                                <ul class="link-list">
                                                    <li><a href=""><em class="icon ni ni-user-alt"></em><span>View Profile</span></a></li>
                                                    <li><a href=""><em class="icon ni ni-setting-alt"></em><span>Account Setting</span></a></li>
                                                </ul>
                                            </div>
                                            <div class="dropdown-inner">
                                                <ul class="link-list">
                                                    <li><a href=""><em class="icon ni ni-signout"></em><span>Sign out</span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- .nk-header-wrap -->
                    </div><!-- .container-fliud -->
                </div>
                <!-- main header @e -->
                <!-- content @s -->
                <div class="nk-content">
                    <div class="container-fluid">
                        <div class="nk-content-inner">
                            <div class="nk-content-body">
                                {% include 'messg/messages.html' %}
                            {% block content %}{% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
                <!-- content @e -->
                <!-- footer @s -->
                <div class="nk-footer">
                    <div class="container-fluid">
                        <div class="nk-footer-wrap">
                            <div class="nk-footer-copyright"> &copy; 2020 Webeights.
                            </div>
                            <div class="nk-footer-links">
                                <ul class="nav nav-sm">
                                    <li class="nav-item"><a class="nav-link" href="#">Terms</a></li>
                                    <li class="nav-item"><a class="nav-link" href="#">Privacy</a></li>
                                    <li class="nav-item"><a class="nav-link" href="#">Help</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- footer @e -->
            </div>
            <!-- wrap @e -->
        </div>
        <!-- main @e -->
    </div>
    <!-- app-root @e -->
    <!-- JavaScript -->
    <script>
        setTimeout(function(){
            if ($('#msg').length > 0) {
                $('#msg').remove();
            }
        }, 3000)
    </script>
    <script src="{% static 'assets-2/assets/js/bundle.js' %}"></script>
    <script src="{% static 'assets-2/assets/js/scripts.js' %}"></script>
    <script src="{% static 'assets-2/assets/js/charts/chart-ecommerce.js' %}"></script>
    <script src="{% static 'assets-2/assets/js/example-toast.js' %}"></script>
    <!-- <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script> -->
    
</body>
</html>